<?php

namespace Aso\GestionUtilisateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
	public function validateEmail($email){
		$query=$this->_em->createQuery("Update AsoGestionUtilisateurBundle:Email e SET e.isValid=true WHERE (e.email='".$email."')");
		return  $query->getOneOrNullResult();
	}
}
