<?php

namespace Aso\GestionUtilisateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaysMondeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysMondeRepository extends EntityRepository
{
}
