<?php

namespace Aso\GestionUtilisateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository {
	public function getMaxId() {
		$query = $this->_em->createQuery ( 'SELECT max(u.id) FROM AsoGestionUtilisateurBundle:Utilisateur u' );
		return $query->getSingleScalarResult ();
	}
	public function getConnexion($identifiant, $secret) {
		$query = $this->_em->createQuery ( "SELECT u, e FROM AsoGestionUtilisateurBundle:Utilisateur u JOIN u.email e WHERE (u.matricule='" . $identifiant . "' OR e.email='" . $identifiant . "') AND (u.password='" . $secret . "' OR e.validationCode='" . $secret . "')" );
		return $query->getOneOrNullResult ();
	}
	public function getUserByIdentifiant($identifiant) {
		$query = $this->_em->createQuery ( "SELECT u, e FROM AsoGestionUtilisateurBundle:Utilisateur u JOIN u.email e WHERE (u.matricule='" . $identifiant . "' OR e.email='" . $identifiant . "')" );
		return $query->getOneOrNullResult ();
	}
	public function getUserById($identifiant) {
		$query = $this->_em->createQuery ( "SELECT u, e FROM AsoGestionUtilisateurBundle:Utilisateur u JOIN u.email e WHERE (u.id=" . $identifiant . ")" );
		return $query->getOneOrNullResult ();
	}
}
