parameters:
#    aso_administration.example.class: Aso\AdministrationBundle\Example

services:
#    aso_administration.example:
#        class: %aso_administration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
